apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deploy
  labels:
    app: webserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webserver-deploy
  template:
    metadata:
      labels:
        name: webserver-deploy
    spec:
      containers:
        - name: webserver
          image: oktaykiraz/webserver
          ports:
          - containerPort: 80
          env:
          - name: MYSQL_PASSWORD
            # value: Clarusway_1
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_admin_password
          envFrom:
            - configMapRef:
                name: server-config
          # - name: MYSQL_USER
          # value: clarus
          # - name: MYSQL_DATABASE
          # value: phonebook 
          # - name: MYSQL_DATABASE_HOST
          # value: mysql-service
          resources: {}

